import AppKit
import Carbon.HIToolbox
import DictationCore
import Foundation

// MARK: - Буфер обмена

/// Запись продиктованного в буфер обмена.
public protocol DictationPasteboard: Sendable {
    /// Сохранить допустимое прежнее содержимое в памяти и положить локальный текст.
    func beginHostOnlyWrite(_ text: String) throws -> PasteboardTransaction
    /// Вернуть прежнее содержимое, только если запись всё ещё принадлежит нам.
    func restore(_ transaction: PasteboardTransaction) throws
}

public struct PasteboardTransaction: Sendable, Equatable {
    fileprivate let id: UUID

    init(id: UUID = UUID()) {
        self.id = id
    }
}

private final class PasteboardTransactionStorage: @unchecked Sendable {
    struct Snapshot {
        let items: [[NSPasteboard.PasteboardType: Data]]
        let ownedChangeCount: Int
    }

    /// Что осталось от транзакции к моменту restore.
    enum Claim {
        /// Snapshot ещё в памяти — восстановление возможно.
        case snapshot(Snapshot)
        /// Privacy budget уже стёр содержимое; остался только счётчик владения.
        /// По нему restore отличает «человек уже скопировал своё» от «прежнее
        /// содержимое потеряно навсегда».
        case expired(ownedChangeCount: Int)
        /// Транзакции не было либо её уже восстановили.
        case missing
    }

    private let lock = NSLock()
    private var snapshots: [UUID: Snapshot] = [:]
    /// Tombstone просроченного snapshot. Содержимого здесь нет — только Int,
    /// поэтому privacy budget не нарушается.
    private var expiredOwnership: [UUID: Int] = [:]
    private let lifetime: TimeInterval

    init(lifetime: TimeInterval) {
        self.lifetime = lifetime
    }

    func insert(_ snapshot: Snapshot, for id: UUID) {
        lock.lock()
        // Вставки идут строго по одной: прежние tombstone больше некому
        // предъявить, и словарь не растёт бесконечно.
        expiredOwnership.removeAll()
        snapshots[id] = snapshot
        lock.unlock()

        // Даже если вызывающая задача погибла между записью и restore,
        // чувствительный snapshot не переживает privacy budget. Три секунды:
        // секунда на потребление ⌘V медленным приложением (VoiceInk #722),
        // до полусекунды на отпускание модификаторов и запас на планировщик.
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + lifetime) { [weak self] in
            self?.expire(id)
        }
    }

    func take(_ id: UUID) -> Claim {
        lock.lock()
        defer { lock.unlock() }
        if let snapshot = snapshots.removeValue(forKey: id) {
            return .snapshot(snapshot)
        }
        if let owned = expiredOwnership.removeValue(forKey: id) {
            return .expired(ownedChangeCount: owned)
        }
        return .missing
    }

    private func expire(_ id: UUID) {
        lock.lock()
        if let snapshot = snapshots.removeValue(forKey: id) {
            expiredOwnership[id] = snapshot.ownedChangeCount
        }
        lock.unlock()
    }
}

/// Буфер обмена, ограниченный этим компьютером.
///
/// Обычная запись отдаёт содержимое в Universal Clipboard, и продиктованный
/// текст оказывается на всех устройствах Apple ID через iCloud — прямо вопреки
/// обещанию продукта. `prepareForNewContents(with: .currentHostOnly)` это
/// отключает, а пометки просят менеджеры буфера не сохранять запись в историю.
///
/// Голый `clearContents()` здесь запрещён, и это проверяется отдельно —
/// `scripts/check-network-surface.sh`.
public struct HostOnlyPasteboard: DictationPasteboard {
    /// Соглашение сторонних менеджеров буфера обмена: «не сохранять».
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Имя доски. В приложении — общая; в тесте своя, чтобы прогон не затирал
    /// то, что человек в этот момент скопировал.
    private let name: String
    private let writeObjects: @Sendable (NSPasteboard, [NSPasteboardWriting]) -> Bool
    private let transactions: PasteboardTransactionStorage

    static let maximumSnapshotBytes = 16 * 1024 * 1024

    /// Содержимое, которое нельзя ни снять, ни восстановить достоверно.
    ///
    /// Всё остальное — включая служебные типы браузеров и мессенджеров —
    /// обычные байты: снимок берёт их как есть и возвращает как есть. Раньше
    /// здесь стоял белый список из пяти типов, и вставка отказывалась после
    /// любого «скопировал из Chrome» — то есть в самом частом состоянии
    /// буфера обмена.
    ///
    /// - Concealed: пароль из менеджера паролей. Его нельзя держать в памяти
    ///   процесса и нельзя потерять — не трогаем буфер вовсе.
    /// - File promise: данные материализуются только в контексте drop;
    ///   снимок обещания не восстановил бы файл.
    static let untouchableTypes: Set<NSPasteboard.PasteboardType> = [
        concealedType,
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-content-type"),
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-url"),
        NSPasteboard.PasteboardType("Apple files promise pasteboard type"),
    ]

    public init(name: String = NSPasteboard.Name.general.rawValue) {
        self.init(name: name, snapshotLifetime: 3) { pasteboard, objects in
            pasteboard.writeObjects(objects)
        }
    }

    init(
        name: String,
        snapshotLifetime: TimeInterval = 3,
        writeObjects: @escaping @Sendable (NSPasteboard, [NSPasteboardWriting]) -> Bool = {
            pasteboard, objects in
            pasteboard.writeObjects(objects)
        }
    ) {
        self.name = name
        self.writeObjects = writeObjects
        self.transactions = PasteboardTransactionStorage(lifetime: snapshotLifetime)
    }

    public func beginHostOnlyWrite(_ text: String) throws -> PasteboardTransaction {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(name))
        let snapshot = try materializeSnapshot(from: pasteboard)
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        let ownedChangeCount = pasteboard.changeCount
        guard writeObjects(pasteboard, [dictatedItem(text)]) else {
            do {
                try restoreSnapshot(snapshot, to: pasteboard, ownedChangeCount: ownedChangeCount)
            } catch {
                throw TextInsertionError.clipboardRestoreFailed
            }
            throw TextInsertionError.clipboardWriteFailed
        }

        let transaction = PasteboardTransaction()
        transactions.insert(
            .init(items: snapshot, ownedChangeCount: pasteboard.changeCount),
            for: transaction.id
        )
        return transaction
    }

    /// Явная команда Copy: пользователь сам разрешил заменить clipboard, но
    /// диктовка всё равно не должна уйти в Universal Clipboard или history.
    public func copyHostOnly(_ text: String) throws {
        try write(text, to: NSPasteboard(name: NSPasteboard.Name(name)))
    }

    public func restore(_ transaction: PasteboardTransaction) throws {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(name))
        // `take` одновременно очищает чувствительный snapshot из памяти — даже
        // когда ownership уже потерян и восстанавливать ничего нельзя.
        switch transactions.take(transaction.id) {
        case let .snapshot(snapshot):
            try restoreSnapshot(
                snapshot.items,
                to: pasteboard,
                ownedChangeCount: snapshot.ownedChangeCount
            )
        case let .expired(ownedChangeCount):
            // Privacy budget уже стёр прежнее содержимое человека. Если человек
            // с тех пор скопировал своё — восстанавливать нечего и это не ошибка.
            guard pasteboard.changeCount == ownedChangeCount else { return }
            // Clipboard всё ещё наш: в нём лежит диктовка. Оставлять её нельзя,
            // а «успех» здесь был бы молчаливой потерей содержимого человека.
            pasteboard.prepareForNewContents(with: .currentHostOnly)
            throw TextInsertionError.clipboardRestoreFailed
        case .missing:
            return
        }
    }

    private func materializeSnapshot(
        from pasteboard: NSPasteboard
    ) throws -> [[NSPasteboard.PasteboardType: Data]] {
        var totalBytes = 0
        var result: [[NSPasteboard.PasteboardType: Data]] = []

        for item in pasteboard.pasteboardItems ?? [] {
            var values: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                guard !Self.untouchableTypes.contains(type) else {
                    throw TextInsertionError.protectedClipboard
                }
                // Тип объявлен, а данных нет — ленивый provider не отдал
                // содержимое. Частичный снимок вернул бы урезанную копию,
                // а молчаливая деградация здесь запрещена.
                guard let data = item.data(forType: type) else {
                    throw TextInsertionError.protectedClipboard
                }
                totalBytes += data.count
                guard totalBytes <= Self.maximumSnapshotBytes else {
                    throw TextInsertionError.protectedClipboard
                }
                values[type] = data
            }
            result.append(values)
        }
        return result
    }

    private func write(_ text: String, to pasteboard: NSPasteboard) throws {
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        guard writeObjects(pasteboard, [dictatedItem(text)]) else {
            throw TextInsertionError.clipboardWriteFailed
        }
    }

    private func dictatedItem(_ text: String) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: Self.transientType)
        item.setString("", forType: Self.concealedType)
        item.setString("", forType: Self.autoGeneratedType)
        return item
    }

    private func restoreSnapshot(
        _ snapshot: [[NSPasteboard.PasteboardType: Data]],
        to pasteboard: NSPasteboard,
        ownedChangeCount: Int
    ) throws {
        guard pasteboard.changeCount == ownedChangeCount else { return }
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        guard !snapshot.isEmpty else { return }
        let restored = snapshot.map { values -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in values { item.setData(data, forType: type) }
            return item
        }
        guard writeObjects(pasteboard, restored) else {
            throw TextInsertionError.clipboardWriteFailed
        }
    }
}

// MARK: - Края системы

/// Всё, что вставка спрашивает у системы и делает с ней.
///
/// За протоколом — потому что настоящие ответы зависят от того, что человек
/// делает за компьютером прямо сейчас: открыто ли поле пароля, какие клавиши
/// зажаты, живо ли приложение, куда мы целимся.
public protocol InputSystem: Sendable {
    /// Защищённый ввод: поле пароля, терминал с защитой клавиатуры, менеджер
    /// паролей. Туда системой запрещено и посылать события, и читать клавиатуру.
    var isSecureInputEnabled: Bool { get }
    var isAccessibilityTrusted: Bool { get }
    func frontmostApplication() -> TargetApplication?
    /// Какие модификаторы зажаты прямо сейчас.
    func heldModifiers() -> CGEventFlags
    /// Вернуть фокус приложению. `false` — приложения больше нет.
    func activate(_ target: TargetApplication) async -> Bool
    func post(keyCode: CGKeyCode, flags: CGEventFlags) throws
}

public struct SystemInput: InputSystem {
    public init() {}

    public var isSecureInputEnabled: Bool { IsSecureEventInputEnabled() }
    public var isAccessibilityTrusted: Bool { AXIsProcessTrusted() }

    public func frontmostApplication() -> TargetApplication? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return TargetApplication(
            bundleIdentifier: app.bundleIdentifier,
            processIdentifier: app.processIdentifier,
            localizedName: app.localizedName
        )
    }

    public func heldModifiers() -> CGEventFlags {
        CGEventSource.flagsState(.combinedSessionState)
    }

    public func activate(_ target: TargetApplication) async -> Bool {
        guard let app = NSRunningApplication(processIdentifier: target.processIdentifier) else {
            return false
        }
        guard !app.isActive else { return true }

        app.activate()
        // Небольшая пауза: переключение фокуса не мгновенно, а нажатие,
        // отправленное раньше времени, уйдёт не туда.
        do {
            try await Task.sleep(for: .milliseconds(120))
        } catch {
            return false
        }
        return true
    }

    public func post(keyCode: CGKeyCode, flags: CGEventFlags) throws {
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else {
            throw TextInsertionError.targetUnavailable
        }

        keyDown.flags = flags
        keyUp.flags = flags
        keyDown.post(tap: .cgSessionEventTap)
        keyUp.post(tap: .cgSessionEventTap)
    }
}

// MARK: - Вставка

/// Вставка распознанного текста в активное приложение.
///
/// Работает через буфер обмена и синтетическое нажатие ⌘V: это единственный
/// способ вставить текст в произвольное приложение, не зная его устройства.
public struct TextInserter: TextInserting {
    /// Модификаторы, отпускания которых мы ждём перед ⌘V.
    ///
    /// Иначе ⌘V смешается с удерживаемым модификатором и превратится в чужое
    /// сочетание — например, в Fn+⌘V, которое приложение поймёт совсем иначе.
    ///
    /// Fn обязателен в списке: это горячая клавиша, доступная в настройках, и
    /// без неё ожидание завершалось бы, пока клавишу ещё держат.
    public static let watchedModifiers: CGEventFlags = [
        .maskCommand, .maskControl, .maskAlternate, .maskShift, .maskSecondaryFn,
    ]

    /// Сколько ждать отпускания и с каким шагом.
    static let releasePollLimit = 50
    static let releasePollInterval = Duration.milliseconds(10)
    /// Пауза между ⌘V и восстановлением буфера.
    ///
    /// 100 мс оказалось мало не по нашей вине: медленные приложения (Electron,
    /// Java, удалённые столы) читают pasteboard в своём цикле событий сотни
    /// миллисекунд спустя — и получали уже ВОССТАНОВЛЕННОЕ старое содержимое
    /// вместо диктовки. Это задокументированный полевой опыт VoiceInk
    /// (issue #722): практический минимум — около секунды.
    static let pasteConsumptionDelay = Duration.milliseconds(1000)

    private let system: any InputSystem
    private let pasteboard: any DictationPasteboard

    public init(
        system: any InputSystem = SystemInput(),
        pasteboard: any DictationPasteboard = HostOnlyPasteboard()
    ) {
        self.system = system
        self.pasteboard = pasteboard
    }

    public func frontmostApplication() -> TargetApplication? {
        system.frontmostApplication()
    }

    /// Обёртка над единственной реализацией.
    ///
    /// Тело ровно одно. Два тела разошлись бы, и витрина скорости показывала бы
    /// путь, которым продукт не ходит.
    public func insert(_ text: String, into target: TargetApplication?) async throws {
        _ = try await insertReportingMarks(text, into: target)
    }

    public func insertReportingMarks(
        _ text: String,
        into target: TargetApplication?
    ) async throws -> InsertionMarks {
        guard !text.isEmpty else { return InsertionMarks() }
        guard let target else { throw TextInsertionError.targetUnavailable }

        // Защищённый ввод — не сбой, а нормальная ситуация.
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }

        // Фокус возвращаем ДО записи в буфер. Если приложения больше нет, дальше
        // идти нельзя, а буфер к этому моменту ещё не тронут: иначе человек
        // терял бы скопированное там, где вставка всё равно не состоялась.
        try await activate(target)
        try validateTarget(target)
        try validateProtectedState()

        let transaction = try pasteboard.beginHostOnlyWrite(text)
        let pasteDispatchedAt: ContinuousClock.Instant
        do {
            try await waitForModifiersRelease()
            // Последняя проверка выполняется после изменения clipboard и прямо
            // перед необратимым событием Cmd+V.
            try validateTarget(target)
            try validateProtectedState()
            try system.post(keyCode: CGKeyCode(kVK_ANSI_V), flags: .maskCommand)
            // Заголовочная отметка: с этого мгновения текст в чужом окне.
            // Всё, что дальше, — защита буфера, и скоростью она не является.
            pasteDispatchedAt = .now
        } catch {
            do {
                try pasteboard.restore(transaction)
            } catch {
                throw TextInsertionError.clipboardRestoreFailed
            }
            throw error
        }

        // Большинство приложений читает pasteboard внутри события, но не все.
        // Задержка — `pasteConsumptionDelay`, то есть секунда: комментарий тут
        // много версий подряд говорил «100 мс» и противоречил своей же
        // константе. Это ожидание, а не работа, и метрикой скорости оно быть
        // не может — отметка вставки снята выше, до сна.
        do {
            try await Task.sleep(for: Self.pasteConsumptionDelay)
        } catch {
            // Cmd+V уже отправлен. Отмена задачи не даёт права оставить
            // продиктованный текст в clipboard до таймера очистки snapshot.
            do {
                try pasteboard.restore(transaction)
            } catch {
                throw TextInsertionError.insertedButClipboardRestoreFailed
            }
            throw TextInsertionError.insertedButClipboardRestoreFailed
        }
        do {
            try pasteboard.restore(transaction)
        } catch {
            throw TextInsertionError.insertedButClipboardRestoreFailed
        }
        return InsertionMarks(
            pasteDispatchedAt: pasteDispatchedAt,
            clipboardRestoredAt: .now
        )
    }

    public func pressReturn() async throws {
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }
        try system.post(keyCode: CGKeyCode(kVK_Return), flags: [])
    }

    /// Вернуть фокус тому приложению, где начиналась диктовка.
    ///
    /// Приложение могли закрыть, пока шло распознавание. Вставлять «куда-нибудь»
    /// в этом случае нельзя: впереди сейчас произвольное окно — вплоть до чужого
    /// поля пароля, — и продиктованное ушло бы туда.
    private func activate(_ target: TargetApplication) async throws {
        guard await system.activate(target) else {
            throw TextInsertionError.targetUnavailable
        }
    }

    private func validateTarget(_ target: TargetApplication) throws {
        guard system.frontmostApplication()?.processIdentifier == target.processIdentifier else {
            throw TextInsertionError.targetChanged
        }
    }

    private func validateProtectedState() throws {
        guard !system.isSecureInputEnabled else {
            throw TextInsertionError.secureInputActive
        }
        guard system.isAccessibilityTrusted else {
            throw TextInsertionError.accessibilityPermissionDenied
        }
    }

    private func waitForModifiersRelease() async throws {
        for _ in 0..<Self.releasePollLimit {
            if system.heldModifiers().intersection(Self.watchedModifiers).isEmpty { return }
            try await Task.sleep(for: Self.releasePollInterval)
        }
        throw TextInsertionError.modifiersStillHeld
    }
}
